FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json pnpm-workspace.yaml turbo.json ./
COPY packages/database ./packages/database
COPY packages/shared-types ./packages/shared-types
COPY apps/web ./apps/web

RUN npm install
RUN npm run build --filter=@trustfundx/web

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/apps/web/public ./public
COPY --from=builder /app/apps/web/.next/standalone ./
COPY --from=builder /app/apps/web/.next/static ./.next/static

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
